version: 2.1

orbs:
  bedrock:
    executors:
      node-10:
        docker:
          - image: 'circleci/node:10-stretch'
      php-73:
        docker:
          - image: 'circleci/php:7.3-stretch'
      php-72:
        docker:
          - image: 'circleci/php:7.2-stretch'
      php-71:
        docker:
          - image: 'circleci/php:7.1-stretch'
    jobs:
      build-php:
        parameters:
          executor:
            type: executor
        executor: << parameters.executor >>
        steps:
          - run: php -v
          - checkout
          - restore_cache:
              keys:
                - composer-v1-{{ checksum "composer.lock" }}
                - composer-v1-
          - run: composer install -n --prefer-dist
          - run: composer test
          - save_cache:
              key: composer-v1-{{ checksum "composer.lock" }}
              paths:
                - vendor

workflows:
  build:
    jobs:
      - bedrock/build-php:
          name: build-php-73
          executor: bedrock/php-73
      - bedrock/build-php:
          name: build-php-72
          executor: bedrock/php-72
      - bedrock/build-php:
          name: build-php-71
          executor: bedrock/php-71
