name: Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: roots/bedrock-docker
        ref: main
        path: bedrock-docker
    - uses: actions/checkout@v4
      with:
        path: bedrock-docker/bedrock
    - name: Build and run
      run: docker compose up --build -d
      working-directory: bedrock-docker
    - name: Wait for install
      run: sleep 30
      working-directory: bedrock-docker
    - name: Verify install
      run: curl -s http://127.0.0.1 | grep "<title>bedrock"
      working-directory: bedrock-docker
